reddit:
  enabled: True
  info: False
  image: True
  video: True
instagram:
  enabled: True
  info: True
  image: True
  thumbnail: False
  video: True
youtube:
  enabled: True
  info: True
  thumbnail: True
tiktok:
  enabled: True
  video: True
respond_to_notice: False
